### ISSUE TITLE
Spam Open Boxes (Actual issue this time)

### ISSUE THREAD

**Issue by FallGuysFan1234** [R3nH4s1ssu3s/RESTORED-blookethacks#2]
Hey R3n! So I have an actual issue to report this time, when I was trying to use spam open boxes on the new dino box that just came out today, it says "I could not find that box!" Here is a screenshot to prove it: 
![image](https://user-images.githubusercontent.com/92480033/167425757-c697da30-a615-4cff-8602-54db68c7f186.png)
I think the spam open boxes script needs to be updated :D

**Comment by R3nH4s1ssu3s** [comment]
it does need to be updated, unfortunately the box just came out so the script wont work. i will try to find a way!
